#!/usr/bin/env bash
# Configures Nginx on a new Ubuntu machine to include a custom X-Served-By header in its HTTP response

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include X-Served-By header
sudo sed -i '/^http {/a \        add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Reload Nginx to apply changes
sudo service nginx reload
