#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80 for all IPv4 addresses
sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
