#!/usr/bin/env bash
# Bash script to configure Nginx to run as nginx user and listen on port 8080

# Set nginx user in nginx.conf
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Modify default Nginx server block to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
